sudo: required
services:
  - docker

before_install:
  - docker build -t mukesh51/docker-react -f Dockerfile.dev .

script:
  - docker run mukesh51/docker-react npm run test -- --coverage

deploy:
  provide: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-405048258426"
  bucket_path: "docker"
  on:
    branch: master